import fs from 'fs/promises';
import { dirname, join, relative } from 'path';
import { fileURLToPath } from 'url';
import { loadSeedCollections, type SeedCollection, type SeedGroup, type SeedStatement } from './seed-content-format.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const DEFAULT_OUTPUT_DIR = join(__dirname, '..', 'specs', 'tech', 'subsystems', 'conceptspace', 'seed-content');

function formatStatement(statement: SeedStatement): string {
  const rolePrefix = statement.role ? `**${statement.role}:** ` : '';
  const lines = [`- ${rolePrefix}"${statement.text}"`];

  for (const note of statement.notes ?? []) {
    lines.push(`  - Note: ${note}`);
  }

  return lines.join('\n');
}

function formatGroup(group: SeedGroup): string {
  const parts = [`## ${group.title}`];

  for (const note of group.notes ?? []) {
    parts.push(`Note: ${note}`);
  }

  parts.push('', 'Statements');
  parts.push(...group.statements.map(formatStatement));

  if ((group.implicationNotes ?? []).length > 0) {
    parts.push('', 'Expected implication links');
    parts.push(...group.implicationNotes!.map((note) => `- ${note}`));
  }

  return parts.join('\n');
}

function renderCollection(collection: SeedCollection, sourceJsonPath: string, outputPath: string): string {
  const relativeSourcePath = relative(dirname(outputPath), sourceJsonPath).replaceAll('\\', '/');

  const parts = [
    `# ${collection.title}`,
    '',
    `> Auto-generated from [\`${relativeSourcePath}\`](${relativeSourcePath}). Do not edit this file by hand; edit the JSON source instead.`,
    '',
    collection.description,
  ];

  if ((collection.notes ?? []).length > 0) {
    parts.push('', 'Collection notes');
    parts.push(...collection.notes!.map((note) => `- ${note}`));
  }

  for (const group of collection.groups) {
    parts.push('', '---', '', formatGroup(group));
  }

  parts.push('');
  return `${parts.join('\n')}\n`;
}

async function main(): Promise<void> {
  const collections = await loadSeedCollections();
  await fs.mkdir(DEFAULT_OUTPUT_DIR, { recursive: true });

  for (const collection of collections) {
    const sourceJsonPath = join(__dirname, 'seed-content', `${collection.id}.json`);
    const outputPath = join(DEFAULT_OUTPUT_DIR, `${collection.id}.md`);
    const markdown = renderCollection(collection, sourceJsonPath, outputPath);
    await fs.writeFile(outputPath, markdown, 'utf8');
    console.log(`Wrote ${outputPath}`);
  }
}

await main();
