import type { Abi } from 'viem';

export const CreatorAssuranceContractFactoryAbi: Abi = [
  { type: 'error', inputs: [], name: 'ArrayLengthMismatch' },
  { type: 'error', inputs: [], name: 'InvalidChannelId' },
  { type: 'error', inputs: [], name: 'InvalidContentIdSeparator' },
  {
    type: 'error',
    inputs: [
      { name: 'channelId', type: 'bytes32' },
      { name: 'canonicalChannelIdHash', type: 'bytes32' },
    ],
    name: 'ChannelCanonicalIdMismatch',
  },
  { type: 'error', inputs: [{ name: 'channelId', type: 'bytes32' }], name: 'ChannelNotVerifiedOrControlled' },
  { type: 'error', inputs: [{ name: 'channelId', type: 'bytes32' }], name: 'ChannelCreatorControlled' },
  { type: 'error', inputs: [], name: 'InsufficientThirdPartyPurchase' },
  { type: 'error', inputs: [], name: 'InitialPurchaseValueMismatch' },
  { type: 'error', inputs: [{ name: 'contentId', type: 'uint256' }], name: 'ContentAlreadyRegisteredForContract' },
  { type: 'error', inputs: [{ name: 'contentId', type: 'uint256' }], name: 'InvalidInitialPurchaseToken' },
  { type: 'error', inputs: [{ name: 'index', type: 'uint256' }], name: 'EmptyContentSuffix' },
  { type: 'error', inputs: [], name: 'ConditionNotFailed' },
  { type: 'error', inputs: [{ name: 'contractAddress', type: 'address' }], name: 'NotCreatorContract' },
  { type: 'error', inputs: [], name: 'MarketplaceCreationFailed' },
  { type: 'error', inputs: [{ name: 'channelId', type: 'bytes32' }], name: 'OnlyChannelOwnerCanCreateCreatorContract' },
  {
    type: 'function',
    name: 'createContract',
    inputs: [
      { name: 'channelId', type: 'bytes32' },
      { name: 'channelCanonicalId', type: 'string' },
      { name: 'contentSuffixes', type: 'string[]' },
      { name: 'supplies', type: 'uint256[]' },
      { name: 'prices', type: 'uint256[]' },
      { name: 'threshold', type: 'uint256' },
      { name: 'deadline', type: 'uint256' },
      { name: 'metadataCid', type: 'string' },
      { name: 'erc1155MetadataUri', type: 'string' },
      { name: 'erc1155ContractUri', type: 'string' },
      { name: 'isThirdParty', type: 'bool' },
      { name: 'initialPurchaseIds', type: 'uint256[]' },
      { name: 'initialPurchaseCounts', type: 'uint256[]' },
    ],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'releaseContentOnFailure',
    inputs: [{ name: 'contractAddress', type: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setThirdPartyMinPurchase',
    inputs: [{ name: '_minPurchase', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'contentRegistry',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'channelRegistry',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'channelEscrow',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'thirdPartyMinPurchase',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'channelIdByContract',
    inputs: [{ name: '', type: 'address' }],
    outputs: [{ name: '', type: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'isThirdPartyCreated',
    inputs: [{ name: '', type: 'address' }],
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'contractCondition',
    inputs: [{ name: '', type: 'address' }],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'contractERC1155',
    inputs: [{ name: '', type: 'address' }],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'CreatorContractCreated',
    inputs: [
      { name: 'contractAddress', type: 'address', indexed: true },
      { name: 'channelId', type: 'bytes32', indexed: true },
      { name: 'creator', type: 'address', indexed: false },
      { name: 'isThirdParty', type: 'bool', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'ThirdPartyMinPurchaseUpdated',
    inputs: [
      { name: 'oldValue', type: 'uint256', indexed: false },
      { name: 'newValue', type: 'uint256', indexed: false },
    ],
  },
] as const;