#!/bin/sh
# Generate runtime config.json from environment so the same image can target
# local / testnet / mainnet without rebuilding JS assets.
set -eu

CONFIG_PATH="${CAUSESTARTER_CONFIG_PATH:-/usr/share/nginx/html/config.json}"

write_kv() {
  key="$1"
  value="$2"
  if [ -n "${value:-}" ]; then
    # Escape backslashes and double quotes for JSON string values.
    escaped=$(printf '%s' "$value" | sed 's/\\/\\\\/g; s/"/\\"/g')
    if [ "$FIRST" = "1" ]; then
      FIRST=0
    else
      printf ',\n' >>"$CONFIG_PATH"
    fi
    printf '  "%s": "%s"' "$key" "$escaped" >>"$CONFIG_PATH"
  fi
}

FIRST=1
printf '{\n' >"$CONFIG_PATH"

write_kv VITE_EVENT_CACHE_URL "${VITE_EVENT_CACHE_URL:-}"
write_kv VITE_IPFS_GATEWAY "${VITE_IPFS_GATEWAY:-}"
write_kv VITE_IPFS_API "${VITE_IPFS_API:-}"
write_kv COMMONALITY_ENVIRONMENT "${COMMONALITY_ENVIRONMENT:-}"
write_kv VITE_PLATFORM_API_URL "${VITE_PLATFORM_API_URL:-}"
write_kv VITE_MAINNET_RPC_URL "${VITE_MAINNET_RPC_URL:-}"
write_kv VITE_ETH_RPC_URL "${VITE_ETH_RPC_URL:-}"
write_kv VITE_BELIEFS_CONTRACT_ADDRESS "${VITE_BELIEFS_CONTRACT_ADDRESS:-}"
write_kv VITE_IMPLICATIONS_CONTRACT_ADDRESS "${VITE_IMPLICATIONS_CONTRACT_ADDRESS:-}"
write_kv VITE_ASSURANCE_CONTRACT_FACTORY_ADDRESS "${VITE_ASSURANCE_CONTRACT_FACTORY_ADDRESS:-}"
write_kv VITE_ERC1155_FACTORY_ADDRESS "${VITE_ERC1155_FACTORY_ADDRESS:-}"
write_kv VITE_DELEGATABLE_NOTES_CONTRACT_ADDRESS "${VITE_DELEGATABLE_NOTES_CONTRACT_ADDRESS:-}"
write_kv VITE_RECURRING_PLEDGES_CONTRACT_ADDRESS "${VITE_RECURRING_PLEDGES_CONTRACT_ADDRESS:-}"
write_kv VITE_NOTE_INTENT_CONTRACT_ADDRESS "${VITE_NOTE_INTENT_CONTRACT_ADDRESS:-}"
write_kv VITE_ALIGNMENT_ATTESTATIONS_CONTRACT_ADDRESS "${VITE_ALIGNMENT_ATTESTATIONS_CONTRACT_ADDRESS:-}"
write_kv VITE_MUTABLE_REF_UPDATER_CONTRACT_ADDRESS "${VITE_MUTABLE_REF_UPDATER_CONTRACT_ADDRESS:-}"
write_kv VITE_TRUST_REGISTRY_CONTRACT_ADDRESS "${VITE_TRUST_REGISTRY_CONTRACT_ADDRESS:-}"
write_kv VITE_NUDGE_PUBLICATIONS_CONTRACT_ADDRESS "${VITE_NUDGE_PUBLICATIONS_CONTRACT_ADDRESS:-}"
write_kv VITE_PUBLISHED_DATA_CONTRACT_ADDRESS "${VITE_PUBLISHED_DATA_CONTRACT_ADDRESS:-}"
write_kv VITE_CONTENT_REGISTRY_ADDRESS "${VITE_CONTENT_REGISTRY_ADDRESS:-}"
write_kv VITE_CHANNEL_REGISTRY_ADDRESS "${VITE_CHANNEL_REGISTRY_ADDRESS:-}"
write_kv VITE_CHANNEL_ESCROW_ADDRESS "${VITE_CHANNEL_ESCROW_ADDRESS:-}"
write_kv VITE_CREATOR_CONTRACT_FACTORY_ADDRESS "${VITE_CREATOR_CONTRACT_FACTORY_ADDRESS:-}"
write_kv VITE_PROJECT_FACTORY_CONTRACT_ADDRESS "${VITE_PROJECT_FACTORY_CONTRACT_ADDRESS:-}"
write_kv VITE_PAYMENT_TOKEN_ADDRESS "${VITE_PAYMENT_TOKEN_ADDRESS:-}"
write_kv VITE_CHAIN_ID "${VITE_CHAIN_ID:-}"
write_kv VITE_PAYMENT_TOKEN_SYMBOL "${VITE_PAYMENT_TOKEN_SYMBOL:-}"
write_kv VITE_PAYMENT_TOKEN_DECIMALS "${VITE_PAYMENT_TOKEN_DECIMALS:-}"
write_kv VITE_COMMONALITY_URL "${VITE_COMMONALITY_URL:-}"
write_kv VITE_LAZYGIVING_URL "${VITE_LAZYGIVING_URL:-}"
write_kv VITE_ALIGNMENT_URL "${VITE_ALIGNMENT_URL:-}"
write_kv VITE_TALLY_URL "${VITE_TALLY_URL:-}"
write_kv VITE_CONTENT_FUNDING_URL "${VITE_CONTENT_FUNDING_URL:-}"
write_kv VITE_CIVILITY_URL "${VITE_CIVILITY_URL:-}"
write_kv VITE_COMMON_SENSE_MAJORITY_URL "${VITE_COMMON_SENSE_MAJORITY_URL:-}"
write_kv VITE_CONCEPTSPACE_URL "${VITE_CONCEPTSPACE_URL:-}"

printf '\n}\n' >>"$CONFIG_PATH"
echo "Wrote CauseStarter runtime config to $CONFIG_PATH"
