/**
 * Invariant checking utilities for integration tests
 *
 * These functions verify that the system maintains consistency properties
 * that should always be true, regardless of what actions are performed.
 *
 * See ../generative-test-prep.md for the full framework.
 */

import assert from 'assert';
import { print } from 'graphql';
import type { TypedDocumentNode } from '@graphql-typed-document-node/core';
import { ActionTestingMachinery } from '../actions/action-machinery.js';
import {
  getIndirectSupporterCount, getIndirectSupporters, SDKMachinery, IpfsCidV1,
  getProject, getProjectContributions, getProjectRefunds,
  getTokenBurns, getNote, getDelegationChain,
  getUserRef, getRef, getUserRefHistory,
  getImplicationsFrom,
  getUserBelief,
  getMarketplaceTrades,
} from '@commonality/sdk';
import { createIsolatedTestClients } from './test-utils.js';
import {
  InvariantGetStatementBelieverCountDocument,
  InvariantGetStatementDisbelieverCountDocument,
  InvariantGetBelieversDocument,
  InvariantGetDisbelieversDocument,
  InvariantGetAllActiveBeliefsDocument,
  InvariantCheckStatementExistsDocument,
  InvariantCheckUserExistsDocument,
  InvariantGetAllImplicationsDocument,
  InvariantCheckAttesterExistsDocument,
} from '../generated/graphql.js';



/**
 * Execute a GraphQL query.
 * Accepts either a TypedDocumentNode (generated by codegen) or a raw query string.
 * When passed a TypedDocumentNode, the result type TData is inferred automatically.
 */
async function executeTypedGraphQLQuery<TData = any, TVars extends Record<string, any> = Record<string, any>>(
  machinery: SDKMachinery,
  document: TypedDocumentNode<TData, TVars> | string,
  variables?: TVars
): Promise<TData> {
  const queryString = typeof document === 'string' ? document : print(document);
  const response = await fetch(machinery.indexerUrl, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      query: queryString,
      variables,
    }),
  });

  if (!response.ok) {
    throw new Error(`GraphQL request failed: ${response.status} ${response.statusText}`);
  }

  const result = await response.json() as { data?: TData; errors?: any[] };

  if (result.errors) {
    throw new Error(`GraphQL errors: ${JSON.stringify(result.errors)}`);
  }

  return result.data as TData;
}

/**
 * State Consistency Invariant #1: Belief counts match belief records
 *
 * For any statement:
 * - believerCount should equal the number of UserBelief records with beliefState=BELIEVES (1)
 * - disbelieverCount should equal the number of UserBelief records with beliefState=DISBELIEVES (2)
 *
 * This checks that the cached aggregated counts on the Statement entity
 * match the actual individual belief records in the database.
 *
 * This is now implemented using the generic assertAggregatedCountConsistency helper,
 * which demonstrates the pattern for checking any cached count against actual records.
 */
export async function assertBeliefCountsMatch(
  machinery: ActionTestingMachinery,
  statementCid: IpfsCidV1
): Promise<void> {
  // Check believerCount using generic helper
  await assertAggregatedCountConsistency(
    machinery,
    InvariantGetStatementBelieverCountDocument,
    { id: statementCid },
    'statements.believerCount',
    InvariantGetBelieversDocument,
    { statementId: statementCid },
    'beliefss.items',
    `Statement ${statementCid}'s believerCount`
  );

  // Check disbelieverCount using generic helper
  await assertAggregatedCountConsistency(
    machinery,
    InvariantGetStatementDisbelieverCountDocument,
    { id: statementCid },
    'statements.disbelieverCount',
    InvariantGetDisbelieversDocument,
    { statementId: statementCid },
    'beliefss.items',
    `Statement ${statementCid}'s disbelieverCount`
  );
}

/**
 * State Consistency Invariant #2: Money conservation
 *
 * For any assurance contract (project):
 * - totalReceived should equal (sum of contributions) - (sum of refunds)
 *
 * This checks that the cached aggregated total on the Project entity
 * matches the sum of all individual Contribution records minus Refund records.
 *
 * Note: This checks money conservation at the indexer level. A more complete
 * check would also verify that the indexer's totalReceived matches the
 * actual ETH balance on the blockchain, but that's a cross-system check
 * (Section 8) rather than a pure state consistency invariant.
 */
export async function assertMoneyConservation(
  machinery: ActionTestingMachinery,
  projectAddress: string
): Promise<void> {
  // Get the project with its cached totalReceived
  const project = await getProject(machinery, projectAddress.toLowerCase());

  if (!project) {
    throw new Error(`Project ${projectAddress} not found`);
  }

  // Get all contributions for this project
  const contributions = await getProjectContributions(machinery, projectAddress.toLowerCase());

  // Get all refunds for this project
  const refunds = await getProjectRefunds(machinery, projectAddress.toLowerCase());

  // Sum up all individual contribution amounts
  const totalContributed = contributions.reduce((sum, contribution) => {
    return sum + BigInt(contribution.totalCost!);
  }, 0n);

  // Sum up all individual refund amounts
  const totalRefunded = refunds.reduce((sum, refund) => {
    return sum + BigInt(refund.totalRefund);
  }, 0n);

  // Calculate expected total: contributions - refunds
  const expectedTotal = totalContributed - totalRefunded;

  const cachedTotal = BigInt(project.totalReceived);

  // Verify the totals match
  assert.strictEqual(
    cachedTotal,
    expectedTotal,
    `Project ${projectAddress}: totalReceived mismatch. ` +
    `Expected ${expectedTotal.toString()} (${totalContributed.toString()} from ${contributions.length} contributions ` +
    `minus ${totalRefunded.toString()} from ${refunds.length} refunds), ` +
    `got ${cachedTotal.toString()} (from cached totalReceived)`
  );
}

/**
 * State Consistency Invariant #3: Token conservation
 *
 * For any project (assurance contract):
 * - For each tokenId: tokens sold (from contributions) should equal tokens held by users + tokens burned
 *
 * This verifies that tokens are neither created nor destroyed incorrectly in the indexer.
 * It checks the accounting equation: Sold = Held + Burned
 *
 * Where:
 * - Sold = sum of tokenCounts from all Contribution records
 * - Burned = sum of tokenCounts from all TokenBurn records
 * - Held = Sold - Burned (implicitly calculated, since we don't track live balances)
 *
 * Note: This is a consistency check at the indexer level. We're verifying that
 * the indexer's view of sold vs burned is internally consistent. A more complete
 * check (Section 8) would also verify against actual ERC1155 balances on-chain.
 *
 * @param graphqlClient GraphQL client or executor
 * @param projectAddress The project's assurance contract address
 */
export async function assertTokenConservation(
  machinery: ActionTestingMachinery,
  projectAddress: string
): Promise<void> {
  // Get all contributions for this project (tokens purchased)
  const contributions = await getProjectContributions(machinery, projectAddress.toLowerCase());
  // Get the ERC1155 address from the first contribution
  // (All contributions for a project should have the same ERC1155 address)
  if (contributions.length === 0) {
    // No contributions yet - nothing to check
    return;
  }

  const erc1155Address = contributions[0].erc1155Address;
  if (!erc1155Address) {
    throw new Error(`Contribution for project ${projectAddress} has no erc1155Address`);
  }

  // Get all token burns for this ERC1155 (tokens destroyed)
  const burns = await getTokenBurns(machinery, erc1155Address.toLowerCase());

  // Calculate total sold and burned per tokenId
  const tokenStats = new Map<string, { sold: bigint; burned: bigint }>();

  // Process contributions (tokens sold)
  for (const contribution of contributions) {
    if (contribution.erc1155Address?.toLowerCase() !== erc1155Address.toLowerCase()) {
      continue; // Skip contributions for different tokens
    }

    const tokenIds = JSON.parse(contribution.tokenIds!) as string[];
    const tokenCounts = JSON.parse(contribution.tokenCounts!) as string[];

    for (let i = 0; i < tokenIds.length; i++) {
      const tokenId = tokenIds[i];
      const count = BigInt(tokenCounts[i]);

      const stats = tokenStats.get(tokenId) || { sold: 0n, burned: 0n };
      stats.sold += count;
      tokenStats.set(tokenId, stats);
    }
  }

  // Process burns (tokens destroyed)
  for (const burn of burns) {
    const tokenIds = JSON.parse(burn.tokenIds) as string[];
    const tokenCounts = JSON.parse(burn.tokenCounts) as string[];

    for (let i = 0; i < tokenIds.length; i++) {
      const tokenId = tokenIds[i];
      const count = BigInt(tokenCounts[i]);

      const stats = tokenStats.get(tokenId) || { sold: 0n, burned: 0n };
      stats.burned += count;
      tokenStats.set(tokenId, stats);
    }
  }

  // Verify conservation for each tokenId
  for (const [tokenId, stats] of tokenStats.entries()) {
    // Check that burned tokens don't exceed sold tokens
    // (Held = Sold - Burned must be >= 0)
    const held = stats.sold - stats.burned;

    assert(
      held >= 0n,
      `ERC1155 ${erc1155Address} tokenId ${tokenId}: Token conservation violation. ` +
      `Burned (${stats.burned.toString()}) exceeds sold (${stats.sold.toString()}). ` +
      `This would mean ${(-held).toString()} tokens were burned that were never purchased.`
    );
  }
}

/**
 * State Consistency Invariant #4: Delegation chain integrity
 *
 * For any delegation note with a chain:
 * - Following the delegation chain should never create a cycle
 * - Each address in the chain should appear exactly once
 * - The chain positions should be sequential (0, 1, 2, ...)
 * - The first position (0) should be the rootOwner
 * - The last position should be the current owner (leaf)
 *
 * This verifies that delegation chains maintain their integrity and don't contain
 * logical inconsistencies like cycles or duplicate addresses.
 *
 * @param graphqlClient GraphQL client or executor
 * @param noteId The delegation note ID to check
 */
export async function assertDelegationChainIntegrity(
  machinery: ActionTestingMachinery,
  noteId: string
): Promise<void> {
  // Get the note
  const note = await getNote(machinery, noteId);
  if (!note) {
    throw new Error(`Note ${noteId} not found`);
  }

  // Get the delegation chain
  const chain = await getDelegationChain(machinery, noteId);

  if (chain.length === 0) {
    // No chain means this is a root note with no delegations
    // Verify that owner === rootOwner
    assert.strictEqual(
      note.owner.toLowerCase(),
      note.rootOwner.toLowerCase(),
      `Note ${noteId}: Root note (no chain) should have owner === rootOwner. ` +
      `Owner: ${note.owner}, RootOwner: ${note.rootOwner}`
    );
    return;
  }

  // Check for duplicate addresses (cycle detection)
  const addressSet = new Set<string>();
  for (const link of chain) {
    const normalizedAddress = link.address.toLowerCase();
    if (addressSet.has(normalizedAddress)) {
      throw new Error(
        `Note ${noteId}: Delegation chain contains cycle. ` +
        `Address ${link.address} appears multiple times in the chain.`
      );
    }
    addressSet.add(normalizedAddress);
  }

  // Check that positions are sequential
  for (let i = 0; i < chain.length; i++) {
    assert.strictEqual(
      chain[i].position,
      i,
      `Note ${noteId}: Chain position mismatch at index ${i}. ` +
      `Expected position ${i}, got ${chain[i].position}`
    );
  }

  // Check that first position (0) is the rootOwner
  assert.strictEqual(
    chain[0].address.toLowerCase(),
    note.rootOwner.toLowerCase(),
    `Note ${noteId}: First chain position (0) should be rootOwner. ` +
    `Chain[0]: ${chain[0].address}, RootOwner: ${note.rootOwner}`
  );

  // Check that last position is the current owner (leaf)
  const lastChainLink = chain[chain.length - 1];
  assert.strictEqual(
    lastChainLink.address.toLowerCase(),
    note.owner.toLowerCase(),
    `Note ${noteId}: Last chain position should be current owner (leaf). ` +
    `Chain[${chain.length - 1}]: ${lastChainLink.address}, Owner: ${note.owner}`
  );
}

/**
 * State Transition Property: Token transfer consistency
 *
 * Section 2 from generative-test-prep.md
 *
 * When tokens are transferred in the secondary market (via trade), verify that:
 * - The trade record has internally consistent data
 * - Buyer and seller are different addresses
 * - Token count is greater than 0
 * - Total price equals count * pricePerToken
 *
 * This is a basic sanity check on trade data. A more complete check would verify
 * actual ERC1155 balance changes on-chain (Section 8: Cross-Subsystem Consistency),
 * but that requires querying the blockchain directly and is more expensive.
 *
 * @param graphqlClient GraphQL client or executor
 * @param marketplaceAddress The marketplace contract address
 * @param transactionHash The transaction hash of the trade to check
 */
export async function assertTradeDataConsistency(
  machinery: ActionTestingMachinery,
  marketplaceAddress: string,
  transactionHash: string
): Promise<void> {
  // Get all trades for this marketplace
  const allTrades = await getMarketplaceTrades(machinery, marketplaceAddress);

  // Find the specific trade by transaction hash
  const trade = allTrades.find(
    t => t.transactionHash.toLowerCase() === transactionHash.toLowerCase()
  );

  if (!trade) {
    throw new Error(
      `Trade not found for marketplace ${marketplaceAddress} ` +
      `in transaction ${transactionHash}`
    );
  }

  // Check that buyer and seller are different
  const buyerNormalized = trade.buyer.toLowerCase();
  const sellerNormalized = trade.seller.toLowerCase();

  assert.notStrictEqual(
    buyerNormalized,
    sellerNormalized,
    `Trade ${trade.id}: Buyer and seller must be different addresses. ` +
    `Both are ${trade.buyer}`
  );

  // Check that count is greater than 0
  const count = BigInt(trade.count);
  assert(
    count > 0n,
    `Trade ${trade.id}: Count must be greater than 0. Got ${count.toString()}`
  );

  // Check that totalPrice = count * pricePerToken
  const pricePerToken = BigInt(trade.pricePerToken);
  const totalPrice = BigInt(trade.totalPrice);
  const expectedTotalPrice = count * pricePerToken;

  assert.strictEqual(
    totalPrice,
    expectedTotalPrice,
    `Trade ${trade.id}: Total price mismatch. ` +
    `Expected ${expectedTotalPrice.toString()} (${count.toString()} * ${pricePerToken.toString()}), ` +
    `got ${totalPrice.toString()}`
  );
}

/**
 * Query Consistency Check: Indirect supporter count vs list
 *
 * Section 3 from generative-test-prep.md
 *
 * Verifies that different ways of querying indirect supporters return consistent results:
 * - The count query should return the same number as the length of the list query
 * - This checks that the indexer's aggregated count matches the actual list of supporters
 *
 * This is a query consistency check (Section 3) rather than a state consistency invariant
 * (Section 1), because it's comparing two different query methods for the same data.
 *
 * @param graphqlClient GraphQL client or executor
 * @param statementId The statement ID to check
 * @param attesterAddress Optional: filter by specific trusted attester
 */
export async function assertIndirectSupporterCountConsistency(
  machinery: ActionTestingMachinery,
  statementCid: IpfsCidV1,
  attesterAddress?: string
): Promise<void> {
  // Method 1: Get the count using the dedicated count query
  const count = await getIndirectSupporterCount(machinery, statementCid, attesterAddress);
  // Method 2: Get the full list of supporters and count them
  const supporters = await getIndirectSupporters(machinery, statementCid, attesterAddress);
  const actualCount = supporters.length;

  // Verify the count matches
  const attesterInfo = attesterAddress ? ` (filtered by attester ${attesterAddress})` : '';
  assert.strictEqual(
    count,
    actualCount,
    `Statement ${statementCid}${attesterInfo}: Indirect supporter count mismatch. ` +
    `Count query returned ${count}, but list query returned ${actualCount} supporters. ` +
    `This indicates a query consistency issue in the indexer.`
  );
}

/**
 * State Consistency Invariant #5: Orphaned data check
 *
 * Section 1 from generative-test-prep.md
 *
 * Verifies that all entity references are valid - i.e., every child entity that references
 * a parent entity has a valid parent that exists in the database. This checks referential
 * integrity across the indexer's data model.
 *
 * Checks performed:
 * - Belief records reference existing Statements and Users
 * - Implication records reference existing Statements (from/to) and Attesters
 * - Project-related records (Contributions, Refunds, etc.) reference existing Projects
 * - Delegation-related records reference existing DelegatableNotes
 * - Cross-subsystem references (DelegatableNote -> Statement, ProjectAlignment -> Project/Statement)
 *
 * This is a fundamental data integrity check that should always pass. If it fails,
 * it indicates a bug in the indexer's event handling logic.
 *
 * Note: This invariant can be expensive to run on large datasets since it queries
 * potentially many entities. Consider running it selectively or with sampling in
 * production generative tests.
 *
 * @param graphqlClient GraphQL client or executor
 */
export async function assertNoOrphanedData(
  machinery: ActionTestingMachinery
): Promise<void> {
  // Check Concept Space subsystem
  await checkOrphanedBeliefs(machinery);
  await checkOrphanedImplications(machinery);
}

/**
 * Check that all Belief records reference valid Statements and Users
 */
async function checkOrphanedBeliefs(
  machinery: ActionTestingMachinery
): Promise<void> {
  // Get all beliefs with a non-zero belief state (active beliefs/disbeliefs)
  const beliefsResult = await executeTypedGraphQLQuery(
    machinery,
    InvariantGetAllActiveBeliefsDocument
  );

  const beliefs = beliefsResult.beliefss?.items || [];

  // Check each belief references a valid statement
  const checkedStatements = new Set<string>();
  const checkedUsers = new Set<string>();

  for (const belief of beliefs) {
    const statementId = belief.statementId.toLowerCase();
    // user is nullable in the schema; skip orphaned beliefs missing a user entity
    if (!belief.user) continue;
    const userId = belief.user.id.toLowerCase();

    // Check statement exists (cache checks to avoid redundant queries)
    if (!checkedStatements.has(statementId)) {
      const statementResult = await executeTypedGraphQLQuery(
        machinery,
        InvariantCheckStatementExistsDocument,
        { id: statementId }
      );

      if (!statementResult.statements) {
        throw new Error(
          `Orphaned Belief: User ${userId} has a belief record for statement ${statementId}, ` +
          `but that statement does not exist in the database. ` +
          `This indicates a referential integrity violation in the indexer.`
        );
      }

      checkedStatements.add(statementId);
    }

    // Check user exists (cache checks to avoid redundant queries)
    if (!checkedUsers.has(userId)) {
      const userResult = await executeTypedGraphQLQuery(
        machinery,
        InvariantCheckUserExistsDocument,
        { id: userId }
      );

      if (!userResult.users) {
        throw new Error(
          `Orphaned Belief: User ${userId} has belief records, ` +
          `but does not exist as a User entity in the database. ` +
          `This indicates a referential integrity violation in the indexer.`
        );
      }

      checkedUsers.add(userId);
    }
  }
}

/**
 * Check that all Implication records reference valid Statements (from/to) and Attesters
 */
async function checkOrphanedImplications(
  machinery: ActionTestingMachinery
): Promise<void> {
  // Get all implications
  const implicationsResult = await executeTypedGraphQLQuery(
    machinery,
    InvariantGetAllImplicationsDocument
  );

  const implications = implicationsResult.implicationss?.items || [];

  // Check each implication references valid entities
  const checkedStatements = new Set<string>();
  const checkedAttesters = new Set<string>();

  for (const implication of implications) {
    const fromId = implication.fromStatementCid.toLowerCase();
    const toId = implication.toStatementCid.toLowerCase();
    // attester is nullable in the schema; skip implications missing one (shouldn't happen in practice)
    if (!implication.attester) continue;
    const attesterId = implication.attester.id.toLowerCase();

    // Check fromStatement exists
    if (!checkedStatements.has(fromId)) {
      const statementResult = await executeTypedGraphQLQuery(
        machinery,
        InvariantCheckStatementExistsDocument,
        { id: fromId }
      );

      if (!statementResult.statements) {
        throw new Error(
          `Orphaned Implication: Attester ${attesterId} attested ${fromId}→${toId}, ` +
          `but source statement ${fromId} does not exist in the database. ` +
          `This indicates a referential integrity violation in the indexer.`
        );
      }

      checkedStatements.add(fromId);
    }

    // Check toStatement exists
    if (!checkedStatements.has(toId)) {
      const statementResult = await executeTypedGraphQLQuery(
        machinery,
        InvariantCheckStatementExistsDocument,
        { id: toId }
      );

      if (!statementResult.statements) {
        throw new Error(
          `Orphaned Implication: Attester ${attesterId} attested ${fromId}→${toId}, ` +
          `but target statement ${toId} does not exist in the database. ` +
          `This indicates a referential integrity violation in the indexer.`
        );
      }

      checkedStatements.add(toId);
    }

    // Check attester exists
    if (!checkedAttesters.has(attesterId)) {
      const attesterResult = await executeTypedGraphQLQuery(
        machinery,
        InvariantCheckAttesterExistsDocument,
        { id: attesterId }
      );

      if (!attesterResult.attesters) {
        throw new Error(
          `Orphaned Implication: Implication ${fromId}→${toId} references attester ${attesterId}, ` +
          `but that attester does not exist in the database. ` +
          `This indicates a referential integrity violation in the indexer.`
        );
      }

      checkedAttesters.add(attesterId);
    }
  }
}

/**
 * Business Logic Constraint: Unique statements (CID-based deduplication)
 *
 * Section 4 from generative-test-prep.md
 *
 * Verifies that statements with identical IPFS content have the same statementId.
 * This checks that the CID-based deduplication is working correctly.
 *
 * In the Commonality system, statement IDs are derived from IPFS content identifiers (CIDs).
 * Two statements with identical content should produce the same CID, and therefore should
 * have the same statementId in the database. This function verifies this property by:
 *
 * 1. Taking two statementIds that are expected to represent identical content
 * 2. Verifying they are actually the same ID (i.e., deduplication occurred)
 *
 * This is primarily a test helper to verify deduplication behavior when creating statements.
 * It's typically called after attempting to create a "duplicate" statement to verify that
 * the system correctly identified it as a duplicate and returned the existing statement's ID.
 *
 * @param statementId1 First statement ID (expected to be identical to statementId2)
 * @param statementId2 Second statement ID (expected to be identical to statementId1)
 * @param context Optional context string for error messages (e.g., "after creating statement with same content")
 */
export async function assertUniqueStatements(
  statementId1: string,
  statementId2: string,
  context?: string
): Promise<void> {
  const contextMsg = context ? ` ${context}` : '';

  assert.strictEqual(
    statementId1.toLowerCase(),
    statementId2.toLowerCase(),
    `Statement uniqueness violation${contextMsg}. ` +
    `Two statements with identical IPFS content should have the same statementId (CID-based deduplication). ` +
    `Got ${statementId1} and ${statementId2}. ` +
    `This indicates that either the CID calculation is non-deterministic or deduplication is not working correctly.`
  );
}

/**
 * Temporal/Historical Property: Monotonic project funding
 *
 * Section 6 from generative-test-prep.md
 *
 * Verifies that a project's totalReceived amount never decreases between two snapshots
 * (unless a refund occurred, in which case the decrease should match the refund amount).
 *
 * This is a temporal property that helps catch bugs in the indexer's event handling.
 * The totalReceived should only ever increase (when contributions are made) or decrease
 * (when refunds are processed). It should never spontaneously change or decrease without
 * a corresponding blockchain event.
 *
 * This function is typically called before and after a sequence of actions to verify that
 * the funding behaves correctly over time.
 *
 * @param graphqlClient GraphQL client or executor
 * @param projectAddress The project's assurance contract address
 * @param expectedBefore The totalReceived value from a previous snapshot
 * @param allowRefunds If true, allows totalReceived to decrease (for tests that include refunds)
 */
export async function assertMonotonicProjectFunding(
  machinery: ActionTestingMachinery,
  projectAddress: string,
  expectedBefore: bigint,
  allowRefunds: boolean = false
): Promise<void> {
  // Get the current project state
  const project = await getProject(machinery, projectAddress.toLowerCase());

  if (!project) {
    throw new Error(`Project ${projectAddress} not found`);
  }

  const currentTotal = BigInt(project.totalReceived);

  if (allowRefunds) {
    // With refunds allowed, we just verify the value is valid (not negative)
    assert(
      currentTotal >= 0n,
      `Project ${projectAddress}: totalReceived became negative: ${currentTotal.toString()}`
    );
  } else {
    // Without refunds, totalReceived should never decrease
    assert(
      currentTotal >= expectedBefore,
      `Project ${projectAddress}: totalReceived decreased without refunds. ` +
      `Expected at least ${expectedBefore.toString()}, got ${currentTotal.toString()}. ` +
      `This violates the monotonic funding property - totalReceived should only increase ` +
      `unless refunds are processed.`
    );
  }
}

/**
 * Business Logic Constraint: Assurance contract refund eligibility
 *
 * Section 4 from generative-test-prep.md
 *
 * Verifies that the refund eligibility rules for assurance contracts are correctly enforced:
 *
 * Refunds ARE allowed when:
 * - The deadline has passed AND the project failed to meet its funding threshold
 *
 * Refunds are NOT allowed when:
 * - The deadline has not passed yet (project fate still undecided)
 * - The deadline has passed AND the project met its threshold (project succeeded)
 *
 * This checks that the business logic constraint matches what the smart contract enforces
 * in AssuranceContract.sol's requireAssuranceContractHasFailed() function.
 *
 * Note: This is a business logic check that verifies the indexer correctly reflects the
 * smart contract's refund rules. The actual refund permission enforcement happens on-chain,
 * but we verify that the indexer's view of project status (totalReceived, threshold, deadline)
 * is consistent with refund eligibility.
 *
 * @param graphqlClient GraphQL client or executor
 * @param projectAddress The project's assurance contract address
 * @param currentBlockTimestamp The current blockchain timestamp (from latest block)
 * @param shouldAllowRefunds Whether refunds should currently be allowed based on contract state
 */
export async function assertAssuranceContractRefundLogic(
  machinery: ActionTestingMachinery,
  projectAddress: string,
  currentBlockTimestamp: bigint,
  shouldAllowRefunds?: boolean
): Promise<void> {
  // Get the project state
  const project = await getProject(machinery, projectAddress.toLowerCase());

  if (!project) {
    throw new Error(`Project ${projectAddress} not found`);
  }

  const totalReceived = BigInt(project.totalReceived);
  const threshold = BigInt(project.threshold);
  const deadline = BigInt(project.deadline);

  // If this project uses a non-EthThreshold condition, threshold and deadline are both 0n
  // (fallback values from on-chain reads). The threshold/deadline-based refund logic doesn't
  // apply in that case, so we skip this invariant check.
  if (threshold === 0n && deadline === 0n) {
    return;
  }

  // Determine if refunds should be allowed based on the business rules
  const deadlineHasPassed = currentBlockTimestamp >= deadline;
  const thresholdWasMet = totalReceived >= threshold;

  // Refunds are allowed if: deadline passed AND threshold NOT met
  const refundsAllowed = deadlineHasPassed && !thresholdWasMet;

  // If the caller provided an expected value, verify it matches our calculation
  if (shouldAllowRefunds !== undefined) {
    assert.strictEqual(
      refundsAllowed,
      shouldAllowRefunds,
      `Project ${projectAddress}: Refund eligibility mismatch. ` +
      `Expected refunds ${shouldAllowRefunds ? 'allowed' : 'not allowed'}, ` +
      `but calculated ${refundsAllowed ? 'allowed' : 'not allowed'}. ` +
      `State: totalReceived=${totalReceived.toString()}, threshold=${threshold.toString()}, ` +
      `deadline=${deadline.toString()}, currentTime=${currentBlockTimestamp.toString()}`
    );
  }

  // Also verify the logical consistency of the state
  // If deadline hasn't passed, refunds must not be allowed
  if (!deadlineHasPassed) {
    assert(
      !refundsAllowed,
      `Project ${projectAddress}: Refunds are allowed before deadline. ` +
      `This violates the business rule that refunds require deadline to pass. ` +
      `Deadline: ${deadline.toString()}, CurrentTime: ${currentBlockTimestamp.toString()}`
    );
  }

  // If threshold was met and deadline passed, refunds must not be allowed
  if (deadlineHasPassed && thresholdWasMet) {
    assert(
      !refundsAllowed,
      `Project ${projectAddress}: Refunds are allowed for successful project. ` +
      `This violates the business rule that successful projects cannot be refunded. ` +
      `TotalReceived: ${totalReceived.toString()}, Threshold: ${threshold.toString()}`
    );
  }

  // If deadline passed and threshold was NOT met, refunds must be allowed
  if (deadlineHasPassed && !thresholdWasMet) {
    assert(
      refundsAllowed,
      `Project ${projectAddress}: Refunds are not allowed for failed project. ` +
      `This violates the business rule that failed projects must allow refunds. ` +
      `TotalReceived: ${totalReceived.toString()}, Threshold: ${threshold.toString()}, ` +
      `Deadline: ${deadline.toString()}, CurrentTime: ${currentBlockTimestamp.toString()}`
    );
  }
}

/**
 * Query Consistency Check: Generic aggregated count vs actual records
 *
 * Section 3 from generative-test-prep.md
 *
 * This is a generic version of the query consistency pattern used throughout the system.
 * It verifies that cached/aggregated counts on parent entities match the actual number
 * of child records when queried directly.
 *
 * This pattern applies to many entity relationships in the system:
 * - Statement.believerCount vs count of Belief records where beliefState=BELIEVES
 * - Statement.disbelieverCount vs count of Belief records where beliefState=DISBELIEVES
 * - Project.contributorCount vs count of distinct contributors in Contribution records
 * - Attester.implicationCount vs count of Implication records
 * - etc.
 *
 * The function takes two queries:
 * 1. A query that returns the cached/aggregated count from a parent entity
 * 2. A query that returns the actual child records to count
 *
 * And verifies that they match. This catches bugs where the indexer's aggregation logic
 * doesn't correctly maintain denormalized counts.
 *
 * @param graphqlClient GraphQL client or executor
 * @param countQuery GraphQL query that returns the cached count (must return single number field)
 * @param countQueryVariables Variables for the count query
 * @param countFieldPath Path to extract count from result (e.g., "statement.believerCount")
 * @param recordsQuery GraphQL query that returns the actual records to count
 * @param recordsQueryVariables Variables for the records query
 * @param recordsFieldPath Path to extract array from result (e.g., "beliefss.items")
 * @param entityDescription Description for error messages (e.g., "Statement X's believerCount")
 */
export async function assertAggregatedCountConsistency(
  machinery: ActionTestingMachinery,
  countQuery: TypedDocumentNode<any, any> | string,
  countQueryVariables: Record<string, any>,
  countFieldPath: string,
  recordsQuery: TypedDocumentNode<any, any> | string,
  recordsQueryVariables: Record<string, any>,
  recordsFieldPath: string,
  entityDescription: string
): Promise<void> {
  const countResult = await executeTypedGraphQLQuery(
    machinery,
    countQuery,
    countQueryVariables
  );

  // Extract the count value using the field path
  const cachedCount = extractFieldByPath(countResult, countFieldPath);
  if (typeof cachedCount !== 'number') {
    throw new Error(
      `Count query for ${entityDescription} did not return a number. ` +
      `Field path "${countFieldPath}" resolved to: ${JSON.stringify(cachedCount)}`
    );
  }

  // Execute the records query
  const recordsResult = await executeTypedGraphQLQuery(
    machinery,
    recordsQuery,
    recordsQueryVariables
  );

  // Extract the records array using the field path
  const records = extractFieldByPath(recordsResult, recordsFieldPath);
  if (!Array.isArray(records)) {
    throw new Error(
      `Records query for ${entityDescription} did not return an array. ` +
      `Field path "${recordsFieldPath}" resolved to: ${JSON.stringify(records)}`
    );
  }

  const actualCount = records.length;

  // Verify the counts match
  assert.strictEqual(
    cachedCount,
    actualCount,
    `${entityDescription}: Aggregated count mismatch. ` +
    `Cached count (${countFieldPath}) is ${cachedCount}, ` +
    `but actual record count (${recordsFieldPath}) is ${actualCount}. ` +
    `This indicates the indexer's denormalized count is out of sync with the actual records.`
  );
}

/**
 * Helper function to extract a nested field from an object using a dot-separated path
 * Example: extractFieldByPath({a: {b: {c: 42}}}, "a.b.c") returns 42
 */
function extractFieldByPath(obj: any, path: string): any {
  const parts = path.split('.');
  let current = obj;

  for (const part of parts) {
    if (current == null) {
      return undefined;
    }
    current = current[part];
  }

  return current;
}

/**
 * State Consistency Invariant: Implication bidirectionality
 *
 * Section 1 from generative-test-prep.md
 *
 * Verifies that the indexer's view of implications is consistent with on-chain reality.
 * If the indexer shows an implication S1→S2 attested by address A, then this implication
 * should be well-formed and internally consistent.
 *
 * This is a data integrity check that ensures the indexer correctly stores and retrieves
 * implication data. It verifies that:
 * - The implication exists in the indexer
 * - All required fields are populated (not null/empty)
 * - The fields match the query parameters (fromStatement, toStatement, attester)
 *
 * Note: In integration tests, the indexer is fed by blockchain events, so the presence
 * of an implication in the indexer implies that the corresponding ImplicationAttested
 * event was emitted and processed. This function verifies the indexer's data integrity
 * rather than querying the blockchain directly (which would be more expensive).
 *
 * @param graphqlClient GraphQL client or executor
 * @param fromStatementCid The source statement ID
 * @param toStatementCid The target statement ID
 * @param attesterAddress The attester's address
 */
export async function assertImplicationBidirectionality(
  machinery: ActionTestingMachinery,
  fromStatementCid: IpfsCidV1,
  toStatementCid: IpfsCidV1,
  attesterAddress: string
): Promise<void> {
  const normalizedAttester = attesterAddress.toLowerCase();

  // Query the indexer for implications from this statement
  const implications = await getImplicationsFrom(machinery, fromStatementCid);

  const implication = implications.find(
    (imp) =>
      imp.toStatementCid === toStatementCid &&
      ((imp.attester as any).id || imp.attester).toLowerCase() === normalizedAttester
  );

  if (!implication) {
    throw new Error(
      `Implication ${fromStatementCid}→${toStatementCid} by ${attesterAddress} not found in indexer. ` +
      `Cannot verify bidirectionality. This function should only be called for implications ` +
      `that are expected to exist.`
    );
  }

  // Verify the implication data is well-formed
  assert.ok(
    implication.fromStatementCid,
    `Implication ${fromStatementCid}→${toStatementCid}: fromStatementCid should not be null/empty`
  );

  assert.ok(
    implication.toStatementCid,
    `Implication ${fromStatementCid}→${toStatementCid}: toStatementCid should not be null/empty`
  );

  assert.ok(
    implication.attester,
    `Implication ${fromStatementCid}→${toStatementCid}: attester should not be null/empty`
  );

  // Verify the IDs match what we queried for (data integrity check)
  assert.strictEqual(
    implication.fromStatementCid,
    fromStatementCid,
    `Implication fromStatementCid mismatch. Expected ${fromStatementCid}, ` +
    `got ${implication.fromStatementCid}`
  );

  assert.strictEqual(
    implication.toStatementCid,
    toStatementCid,
    `Implication toStatementCid mismatch. Expected ${toStatementCid}, ` +
    `got ${implication.toStatementCid}`
  );

  const attesterIdFromResponse = (implication.attester as any).id || implication.attester;
  assert.strictEqual(
    attesterIdFromResponse.toLowerCase(),
    normalizedAttester,
    `Implication attester mismatch. Expected ${attesterAddress}, ` +
    `got ${attesterIdFromResponse}`
  );
}

/**
 * Business Logic Constraint: Implication non-transitivity
 *
 * Section 4 from generative-test-prep.md
 *
 * Verifies that the system correctly implements non-transitive implication semantics.
 * Just because S1→S2 and S2→S3 exist doesn't mean the system should automatically
 * show S1's believers as indirect supporters of S3. There must be a DIRECT attestation
 * of S1→S3 for that support to propagate.
 *
 * This is a fundamental business rule that prevents unintended support propagation
 * through long implication chains. For example:
 * - Alice believes "I support climate action" (S1)
 * - Attester says S1→"I support carbon taxes" (S2)
 * - Attester says S2→"I support $500/ton carbon tax" (S3)
 *
 * Alice should appear as an indirect supporter of S2 (one hop), but NOT S3 (two hops),
 * unless there's a direct S1→S3 attestation.
 *
 * This function verifies the non-transitivity property by:
 * 1. Checking that S1→S2 and S2→S3 implications exist
 * 2. Verifying that NO S1→S3 implication exists
 * 3. Confirming that believers of S1 appear as indirect supporters of S2
 * 4. Confirming that believers of S1 do NOT appear as indirect supporters of S3
 *
 * @param graphqlClient GraphQL client or executor
 * @param s1Id Statement ID for the first statement (source)
 * @param s2Id Statement ID for the middle statement
 * @param s3Id Statement ID for the third statement (target)
 * @param attesterAddress Address of the attester who created the implications
 * @param believerAddress Address of a user who believes S1 (for verification)
 */
export async function assertImplicationNonTransitivity(
  machinery: ActionTestingMachinery,
  s1Cid: IpfsCidV1,
  s2Cid: IpfsCidV1,
  s3Cid: IpfsCidV1,
  attesterAddress: string,
  believerAddress: string
): Promise<void> {
  // Import SDK constants and query functions dynamically to avoid circular dependencies
  const { BELIEVES, DISBELIEVES } = await import('@commonality/sdk');
  const normalizedAttester = attesterAddress.toLowerCase();
  const normalizedBeliever = believerAddress.toLowerCase();

  // Step 1: Verify S1→S2 implication exists
  const implicationsFromS1 = await getImplicationsFrom(machinery, s1Cid);
  const s1ToS2 = implicationsFromS1.find(
    (imp) =>
      imp.toStatementCid === s2Cid &&
      ((imp.attester as any).id || imp.attester).toLowerCase() === normalizedAttester
  );

  assert.ok(
    s1ToS2,
    `Non-transitivity test setup error: S1→S2 implication should exist. ` +
    `Attester ${attesterAddress} has not attested ${s1Cid}→${s2Cid}`
  );

  // Step 2: Verify S2→S3 implication exists
  const implicationsFromS2 = await getImplicationsFrom(machinery, s2Cid);
  const s2ToS3 = implicationsFromS2.find(
    (imp) =>
      imp.toStatementCid === s3Cid &&
      ((imp.attester as any).id || imp.attester).toLowerCase() === normalizedAttester
  );

  assert.ok(
    s2ToS3,
    `Non-transitivity test setup error: S2→S3 implication should exist. ` +
    `Attester ${attesterAddress} has not attested ${s2Cid}→${s3Cid}`
  );

  // Step 3: Verify NO S1→S3 implication exists (critical for this test)
  const s1ToS3 = implicationsFromS1.find(
    (imp) =>
      imp.toStatementCid === s3Cid &&
      ((imp.attester as any).id || imp.attester).toLowerCase() === normalizedAttester
  );

  assert.ok(
    !s1ToS3,
    `Non-transitivity test setup error: S1→S3 implication should NOT exist. ` +
    `Found unexpected direct attestation ${s1Cid}→${s3Cid} by ${attesterAddress}. ` +
    `This test requires S1→S2 and S2→S3 to exist WITHOUT a direct S1→S3.`
  );

  // Step 4: Verify the believer believes S1
  const believerS1Belief = await getUserBelief(machinery, normalizedBeliever, s1Cid);
  assert.strictEqual(
    believerS1Belief?.beliefState,
    BELIEVES,
    `Non-transitivity test setup error: User ${believerAddress} should believe S1 (${s1Cid}). ` +
    `Got beliefState: ${believerS1Belief?.beliefState}`
  );

  // Step 5: Verify the believer does NOT explicitly disbelieve S2 or S3
  // (If they disbelieve, they won't appear as indirect supporters regardless)
  const believerS2Belief = await getUserBelief(machinery, normalizedBeliever, s2Cid);
  assert.notStrictEqual(
    believerS2Belief?.beliefState,
    DISBELIEVES,
    `Non-transitivity test setup error: User ${believerAddress} should NOT disbelieve S2 (${s2Cid}). ` +
    `This would prevent them from appearing as indirect supporter.`
  );

  const believerS3Belief = await getUserBelief(machinery, normalizedBeliever, s3Cid);
  assert.notStrictEqual(
    believerS3Belief?.beliefState,
    DISBELIEVES,
    `Non-transitivity test setup error: User ${believerAddress} should NOT disbelieve S3 (${s3Cid}). ` +
    `This would prevent them from appearing as indirect supporter.`
  );

  // Step 6: Verify believer appears as indirect supporter of S2 (one hop: S1→S2)
  const s2IndirectSupporters = await getIndirectSupporters(machinery, s2Cid, normalizedAttester);
  const s2SupporterAddresses = s2IndirectSupporters.map(s => s.user.toLowerCase());

  assert.ok(
    s2SupporterAddresses.includes(normalizedBeliever),
    `Implication transitivity violation: User ${believerAddress} believes S1 (${s1Cid}), ` +
    `and S1→S2 exists, so they should appear as indirect supporter of S2 (${s2Cid}). ` +
    `Found ${s2IndirectSupporters.length} indirect supporters, ` +
    `but ${believerAddress} is not among them: [${s2SupporterAddresses.join(', ')}]`
  );

  // Step 7: Verify believer does NOT appear as indirect supporter of S3 (two hops: S1→S2→S3)
  // This is the CORE non-transitivity check
  const s3IndirectSupporters = await getIndirectSupporters(machinery, s3Cid, normalizedAttester);
  const s3SupporterAddresses = s3IndirectSupporters.map(s => s.user.toLowerCase());

  assert.ok(
    !s3SupporterAddresses.includes(normalizedBeliever),
    `Implication NON-transitivity violation: User ${believerAddress} believes S1 (${s1Cid}), ` +
    `and we have S1→S2 and S2→S3 (but NO direct S1→S3), so they should NOT appear ` +
    `as indirect supporter of S3 (${s3Cid}). The system incorrectly propagated support ` +
    `through TWO hops. This violates the business rule that implications are non-transitive. ` +
    `Found ${s3IndirectSupporters.length} indirect supporters of S3: [${s3SupporterAddresses.join(', ')}], ` +
    `and ${believerAddress} should NOT be in this list.`
  );
}

/**
 * State Consistency Invariant: Ref contract-indexer consistency
 *
 * Section 1 from generative-test-prep.md
 *
 * Verifies that the value of a mutable ref in the indexer matches the value
 * stored directly on the blockchain contract. This checks that the indexer
 * correctly tracks ref updates.
 *
 * This is a cross-subsystem consistency check (Section 8) that ensures the
 * indexer's view of mutable refs matches the on-chain state.
 *
 * @param graphqlClient GraphQL client or executor
 * @param mutableRefContract The MutableRefUpdater contract instance
 * @param userAddress The owner of the ref
 * @param refName The name of the ref to check
 */
export async function assertRefContractIndexerConsistency(
  machinery: ActionTestingMachinery,
  mutableRefContract: any,
  userAddress: string,
  refName: string
): Promise<void> {
  // Get value from indexer
  const indexerRef = await getUserRef(machinery, userAddress, refName);
  const indexerValue = indexerRef?.value ?? '';

  // Get value from contract - we need to create a minimal clients object
  // For read-only operations, we can use a public client
  const clients = createIsolatedTestClients('ref-check', 0, process.env.RPC_URL || 'http://localhost:8545');
  const contractValue = await getRef(clients, mutableRefContract, userAddress as `0x${string}`, refName);

  // Verify they match
  assert.strictEqual(
    indexerValue,
    contractValue,
    `Ref ${refName} for user ${userAddress}: Indexer value doesn't match contract value. ` +
    `Indexer: "${indexerValue}", Contract: "${contractValue}". ` +
    `This indicates the indexer is out of sync with the blockchain.`
  );
}

/**
 * State Consistency Invariant: Ref history ordering
 *
 * Section 1 from generative-test-prep.md
 *
 * Verifies that the history entries for a mutable ref are properly ordered.
 * The history should be sorted by block number and transaction index, with
 * newer entries appearing first (reverse chronological order).
 *
 * This checks that the indexer correctly maintains temporal ordering of events.
 *
 * @param graphqlClient GraphQL client or executor
 * @param userAddress The owner of the ref
 * @param refName The name of the ref to check
 */
export async function assertRefHistoryOrdering(
  machinery: ActionTestingMachinery,
  userAddress: string,
  refName: string
): Promise<void> {
  // Get history
  const history = await getUserRefHistory(machinery, userAddress, refName);

  // Check that history is in reverse chronological order (newest first)
  // Each entry should have a blockNumber and transactionIndex
  for (let i = 0; i < history.length - 1; i++) {
    const current = history[i];
    const next = history[i + 1];

    // Compare block numbers
    const currentBlock = BigInt(current.blockNumber);
    const nextBlock = BigInt(next.blockNumber);

    if (currentBlock < nextBlock) {
      throw new Error(
        `Ref ${refName} for user ${userAddress}: History ordering violation. ` +
        `Entry at index ${i} has blockNumber ${currentBlock}, ` +
        `but entry at index ${i + 1} has blockNumber ${nextBlock}. ` +
        `History should be in reverse chronological order (newest first).`
      );
    }

    // If same block, compare log indices (lower logIndex = earlier in block)
    if (currentBlock === nextBlock) {
      const currentLogIndex = current.logIndex ?? 0;
      const nextLogIndex = next.logIndex ?? 0;

      if (currentLogIndex < nextLogIndex) {
        throw new Error(
          `Ref ${refName} for user ${userAddress}: History ordering violation within block ${currentBlock}. ` +
          `Entry at index ${i} has logIndex ${currentLogIndex}, ` +
          `but entry at index ${i + 1} has logIndex ${nextLogIndex}. ` +
          `Within the same block, history should be ordered by log index (newest first).`
        );
      }
    }
  }
}
