#!/usr/bin/env bash
#
# One-command setup for GitHub Actions secrets.
# Extracts required secrets from local files and prints gh CLI commands to set them.
#
# Usage:
#   ./scripts/setup-github-secrets.sh
#
# Prerequisites:
#   - GitHub CLI (gh) installed and authenticated
#   - Local .env.secrets file (generated by scripts/generate-wallets.mjs)
#   - Operator secrets file (~/.secrets/commonality/operator.env)
#   - deployments/base-sepolia.env (from contract deployment)
#
# This script does NOT modify your repository — it only prints commands.
# Review the output, then run the commands if they look correct.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck source=scripts/lib/secrets.sh
source "$ROOT/scripts/lib/secrets.sh"

echo "═══════════════════════════════════════════════════════════════"
echo "  GitHub Secrets Setup Helper"
echo "═══════════════════════════════════════════════════════════════"
echo ""

# Check prerequisites
if ! command -v gh &>/dev/null; then
  echo "❌ Error: GitHub CLI (gh) not found."
  echo "   Install: https://cli.github.com/"
  echo "   Then run: gh auth login"
  exit 1
fi

if ! gh auth status &>/dev/null; then
  echo "❌ Error: Not authenticated with GitHub CLI."
  echo "   Run: gh auth login"
  exit 1
fi

SECRETS_FILE="$(commonality_service_secrets_file)"
OPERATOR_FILE="$(commonality_operator_secrets_file)"

if [ ! -f "$SECRETS_FILE" ]; then
  echo "❌ Error: Service secrets file not found: $SECRETS_FILE"
  echo "   Run: node scripts/generate-wallets.mjs"
  exit 1
fi

if [ ! -f "$OPERATOR_FILE" ]; then
  echo "❌ Error: Operator secrets file not found: $OPERATOR_FILE"
  echo "   Run: node scripts/generate-wallets.mjs"
  echo "   Or set COMMONALITY_OPERATOR_SECRETS_FILE environment variable"
  exit 1
fi

echo "✅ Found service secrets: $SECRETS_FILE"
echo "✅ Found operator secrets: $OPERATOR_FILE"
echo ""

# Helper function to extract value from files
get_value() {
  local key="$1"
  local value
  value=$(commonality_env_value "$key" "$OPERATOR_FILE" "$SECRETS_FILE")
  if [ -z "$value" ]; then
    echo "⚠️  WARNING: $key not found in any secrets file"
    return 1
  fi
  echo "$value"
}

# Collect all secrets
echo "Collecting secrets..."
echo ""

declare -A SECRETS

# Contract deployment secrets
echo "  📝 Contract deployment secrets..."
SECRETS[DEPLOYER_PRIVATE_KEY]=$(get_value DEPLOYER_PRIVATE_KEY || echo "")
SECRETS[BASE_SEPOLIA_RPC_URL]=$(get_value BASE_SEPOLIA_RPC_URL || echo "")

# Get CONTRACT_ADMIN_ADDRESS from deployments/operator-addresses.env
OPERATOR_ADDRESSES="$ROOT/deployments/operator-addresses.env"
if [ -f "$OPERATOR_ADDRESSES" ]; then
  SECRETS[CONTRACT_ADMIN_ADDRESS]=$(grep -E '^CONTRACT_ADMIN_ADDRESS=' "$OPERATOR_ADDRESSES" | tail -1 | cut -d= -f2- || echo "")
else
  echo "⚠️  WARNING: $OPERATOR_ADDRESSES not found"
  SECRETS[CONTRACT_ADMIN_ADDRESS]=""
fi

# UI deployment secrets
echo "  📝 UI deployment secrets..."
SECRETS[PINATA_JWT]=$(get_value PINATA_JWT || echo "")

# IPNS keys for all domains
DOMAINS=(COMMONALITY LAZYGIVING ALIGNMENT TALLY CONTENT_FUNDING CIVILITY COMMON_SENSE_MAJORITY CONCEPTSPACE)
for domain in "${DOMAINS[@]}"; do
  var_name="IPNS_PRIVATE_KEY_TESTNET_${domain}"
  SECRETS[$var_name]=$(get_value "$var_name" || echo "")
done

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "  Review Required Secrets"
echo "═══════════════════════════════════════════════════════════════"
echo ""

# Check for missing secrets
MISSING=()
for key in "${!SECRETS[@]}"; do
  if [ -z "${SECRETS[$key]}" ]; then
    MISSING+=("$key")
  fi
done

if [ ${#MISSING[@]} -gt 0 ]; then
  echo "❌ Missing secrets:"
  for key in "${MISSING[@]}"; do
    echo "   - $key"
  done
  echo ""
  echo "Please ensure these values are set in:"
  echo "  - $OPERATOR_FILE"
  echo "  - $SECRETS_FILE"
  echo "  - $OPERATOR_ADDRESSES"
  echo ""
  echo "Then re-run this script."
  exit 1
fi

echo "✅ All required secrets found!"
echo ""
echo "The following secrets will be set in GitHub:"
echo ""

for key in $(echo "${!SECRETS[@]}" | tr ' ' '\n' | sort); do
  value="${SECRETS[$key]}"
  # Mask the value for display
  if [ ${#value} -gt 20 ]; then
    masked="${value:0:8}...${value: -4}"
  else
    masked="****"
  fi
  printf "  %-50s %s\n" "$key" "$masked"
done

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "  Commands to Set Secrets"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Copy and run these commands to set the secrets:"
echo ""

# Generate gh secret set commands
for key in $(echo "${!SECRETS[@]}" | tr ' ' '\n' | sort); do
  value="${SECRETS[$key]}"
  # Use printf to handle special characters safely
  printf 'gh secret set %s --body "%s"\n' "$key" "$value"
done

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "  Alternative: Interactive Mode"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Or use interactive mode (prompts for each secret):"
echo ""
echo "  gh secret set DEPLOYER_PRIVATE_KEY"
echo "  gh secret set BASE_SEPOLIA_RPC_URL"
echo "  gh secret set CONTRACT_ADMIN_ADDRESS"
echo "  gh secret set PINATA_JWT"
echo "  gh secret set IPNS_PRIVATE_KEY_TESTNET_COMMONALITY"
echo "  gh secret set IPNS_PRIVATE_KEY_TESTNET_LAZYGIVING"
echo "  gh secret set IPNS_PRIVATE_KEY_TESTNET_ALIGNMENT"
echo "  gh secret set IPNS_PRIVATE_KEY_TESTNET_TALLY"
echo "  gh secret set IPNS_PRIVATE_KEY_TESTNET_CONTENT_FUNDING"
echo "  gh secret set IPNS_PRIVATE_KEY_TESTNET_CIVILITY"
echo "  gh secret set IPNS_PRIVATE_KEY_TESTNET_COMMON_SENSE_MAJORITY"
echo "  gh secret set IPNS_PRIVATE_KEY_TESTNET_CONCEPTSPACE"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "  Done!"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "After setting secrets:"
echo "  1. Verify Render is watching master branch"
echo "  2. Make a small change and merge to master to test"
echo "  3. Watch: https://github.com/AdamSpitz/commonality/actions"
echo ""
