#!/usr/bin/env bash
#
# Combines .env.secrets + deployments/<network>.env + defaults into the .env
# files that each service reads.
#
# Usage:
#   ./scripts/setup-env.sh [network]
#
# network: localhost (default), sepolia, mainnet

set -euo pipefail

NETWORK="${1:-localhost}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"

SECRETS_FILE="$ROOT/.env.secrets"
DEPLOYMENT_FILE="$ROOT/deployments/${NETWORK}.env"

if [ ! -f "$SECRETS_FILE" ]; then
  echo "Error: $SECRETS_FILE not found."
  echo "Copy .env.secrets.example to .env.secrets and fill in your values."
  exit 1
fi

if [ ! -f "$DEPLOYMENT_FILE" ]; then
  echo "Error: $DEPLOYMENT_FILE not found."
  echo "Deploy contracts first: cd hardhat && npx hardhat run scripts/deploy.js --network $NETWORK"
  exit 1
fi

# --- Helper: read a var from a file (ignoring comments/blanks) ---
read_var() {
  local file="$1" key="$2"
  grep -E "^${key}=" "$file" 2>/dev/null | tail -1 | cut -d= -f2-
}

# --- Load secrets and deployment vars into associative array ---
declare -A VARS

# Load deployment addresses
while IFS= read -r line; do
  [[ "$line" =~ ^#.*$ || -z "$line" ]] && continue
  key="${line%%=*}"
  value="${line#*=}"
  VARS["$key"]="$value"
done < "$DEPLOYMENT_FILE"

# Load secrets (these override deployment vars if there's overlap)
while IFS= read -r line; do
  [[ "$line" =~ ^#.*$ || -z "$line" ]] && continue
  key="${line%%=*}"
  value="${line#*=}"
  VARS["$key"]="$value"
done < "$SECRETS_FILE"

# --- Aliases (deployment files use one name; integration tests use another) ---
VARS[PROJECT_ALIGNMENT_CONTRACT_ADDRESS]="${VARS[PROJECT_ALIGNMENT_CONTRACT_ADDRESS]:-${VARS[ALIGNMENT_ATTESTATIONS_CONTRACT_ADDRESS]}}"

# --- Network-specific defaults ---
case "$NETWORK" in
  localhost)
    VARS[ETHEREUM_RPC_URL]="${VARS[ETHEREUM_RPC_URL]:-http://localhost:8545}"
    VARS[IPFS_API]="${VARS[IPFS_API]:-http://localhost:5001}"
    VARS[IPFS_GATEWAY]="${VARS[IPFS_GATEWAY]:-http://localhost:8080/ipfs}"
    VARS[VITE_GRAPHQL_URL]="${VARS[VITE_GRAPHQL_URL]:-http://localhost:42069/graphql}"
    VARS[EVENT_CACHE_URL]="${VARS[EVENT_CACHE_URL]:-http://localhost:42069}"
    ;;
  sepolia)
    VARS[SEPOLIA_RPC_URL]="${VARS[SEPOLIA_RPC_URL]:-https://rpc.sepolia.org}"
    VARS[ETHEREUM_RPC_URL]="${VARS[ETHEREUM_RPC_URL]:-${VARS[SEPOLIA_RPC_URL]}}"
    VARS[IPFS_API]="${VARS[IPFS_API]:-https://ipfs.io/api/v0}"
    VARS[IPFS_GATEWAY]="${VARS[IPFS_GATEWAY]:-https://ipfs.io/ipfs}"
    ;;
  mainnet)
    VARS[MAINNET_RPC_URL]="${VARS[MAINNET_RPC_URL]:-https://eth.llamarpc.com}"
    VARS[ETHEREUM_RPC_URL]="${VARS[ETHEREUM_RPC_URL]:-${VARS[MAINNET_RPC_URL]}}"
    VARS[IPFS_API]="${VARS[IPFS_API]:-https://ipfs.io/api/v0}"
    VARS[IPFS_GATEWAY]="${VARS[IPFS_GATEWAY]:-https://ipfs.io/ipfs}"
    ;;
  *)
    echo "Unknown network: $NETWORK (expected: localhost, sepolia, mainnet)"
    exit 1
    ;;
esac

# ============================================================
# 1. Root .env — used by docker-compose, hardhat, indexer
# ============================================================
echo "# Auto-generated by scripts/setup-env.sh for network: $NETWORK" > "$ROOT/.env"
echo "# Do not edit — re-run the script to regenerate." >> "$ROOT/.env"
echo "" >> "$ROOT/.env"

ROOT_VARS=(
  DEPLOYER_PRIVATE_KEY
  SEPOLIA_RPC_URL MAINNET_RPC_URL ETHEREUM_RPC_URL ETHERSCAN_API_KEY
  BELIEFS_CONTRACT_ADDRESS IMPLICATIONS_CONTRACT_ADDRESS
  ALIGNMENT_ATTESTATIONS_CONTRACT_ADDRESS ALIGNMENT_ATTESTATIONS_ADDRESS
  PROJECT_ALIGNMENT_CONTRACT_ADDRESS
  DELEGATABLE_NOTES_CONTRACT_ADDRESS DELEGATABLE_NOTES_ADDRESS
  MUTABLE_REF_UPDATER_CONTRACT_ADDRESS MUTABLE_REF_UPDATER_ADDRESS
  ASSURANCE_CONTRACT_FACTORY_ADDRESS ERC1155_FACTORY_ADDRESS
  MARKETPLACE_FACTORY_ADDRESS NOTE_INTENT_ADDRESS PUBSTARTER_ADDRESS
  CHANNEL_VERIFIER_ADDRESS CONTENT_REGISTRY_ADDRESS CHANNEL_REGISTRY_ADDRESS
  CHANNEL_ESCROW_ADDRESS CREATOR_CONTRACT_FACTORY_ADDRESS
  START_BLOCK CONTENT_FUNDING_START_BLOCK
  IPFS_API IPFS_GATEWAY
  EVENT_CACHE_URL
  NUM_USERS NUM_ROUNDS
)

for key in "${ROOT_VARS[@]}"; do
  [ -n "${VARS[$key]+x}" ] && echo "${key}=${VARS[$key]}" >> "$ROOT/.env"
done

echo "  wrote $ROOT/.env"

# ============================================================
# 2. integration-tests/.env.local — same as root .env
# ============================================================
cp "$ROOT/.env" "$ROOT/integration-tests/.env.local"
echo "  wrote $ROOT/integration-tests/.env.local"

# ============================================================
# 3. ui/.env — VITE_-prefixed vars + contract addresses
# ============================================================
{
  echo "# Auto-generated by scripts/setup-env.sh for network: $NETWORK"
  echo "# Do not edit — re-run the script to regenerate."
  echo ""
  echo "VITE_WALLETCONNECT_PROJECT_ID=${VARS[VITE_WALLETCONNECT_PROJECT_ID]:-}"
  echo "VITE_GRAPHQL_URL=${VARS[VITE_GRAPHQL_URL]:-}"
  echo "VITE_BELIEFS_CONTRACT_ADDRESS=${VARS[BELIEFS_CONTRACT_ADDRESS]:-}"
  echo "VITE_IMPLICATIONS_CONTRACT_ADDRESS=${VARS[IMPLICATIONS_CONTRACT_ADDRESS]:-}"
  echo "VITE_MUTABLE_REF_UPDATER_CONTRACT_ADDRESS=${VARS[MUTABLE_REF_UPDATER_CONTRACT_ADDRESS]:-}"
  echo "VITE_DELEGATABLE_NOTES_CONTRACT_ADDRESS=${VARS[DELEGATABLE_NOTES_CONTRACT_ADDRESS]:-}"
  echo "VITE_NOTE_INTENT_CONTRACT_ADDRESS=${VARS[NOTE_INTENT_ADDRESS]:-}"
  echo "VITE_ASSURANCE_CONTRACT_FACTORY_ADDRESS=${VARS[ASSURANCE_CONTRACT_FACTORY_ADDRESS]:-}"
  echo "VITE_ERC1155_FACTORY_ADDRESS=${VARS[ERC1155_FACTORY_ADDRESS]:-}"
  echo "VITE_MARKETPLACE_FACTORY_ADDRESS=${VARS[MARKETPLACE_FACTORY_ADDRESS]:-}"
  echo "VITE_ALIGNMENT_ATTESTATIONS_CONTRACT_ADDRESS=${VARS[ALIGNMENT_ATTESTATIONS_CONTRACT_ADDRESS]:-}"
  echo "VITE_TRUST_REGISTRY_CONTRACT_ADDRESS=${VARS[TRUST_REGISTRY_CONTRACT_ADDRESS]:-}"
  echo "VITE_IPFS_GATEWAY=${VARS[IPFS_GATEWAY]:-}"
  echo "VITE_IPFS_API=${VARS[IPFS_API]:-}"
  echo "VITE_CONTENT_REGISTRY_ADDRESS=${VARS[CONTENT_REGISTRY_ADDRESS]:-}"
  echo "VITE_CHANNEL_REGISTRY_ADDRESS=${VARS[CHANNEL_REGISTRY_ADDRESS]:-}"
  echo "VITE_CHANNEL_ESCROW_ADDRESS=${VARS[CHANNEL_ESCROW_ADDRESS]:-}"
  echo "VITE_CREATOR_CONTRACT_FACTORY_ADDRESS=${VARS[CREATOR_CONTRACT_FACTORY_ADDRESS]:-}"
} > "$ROOT/ui/.env"

echo "  wrote $ROOT/ui/.env"

# ============================================================
# 4. attester/.env — attester-specific vars
# ============================================================
{
  echo "# Auto-generated by scripts/setup-env.sh for network: $NETWORK"
  echo "# Do not edit — re-run the script to regenerate."
  echo ""
  echo "ETHEREUM_RPC_URL=${VARS[ETHEREUM_RPC_URL]:-}"
  echo "ATTESTER_PRIVATE_KEY=${VARS[ATTESTER_PRIVATE_KEY]:-}"
  echo "IMPLICATIONS_CONTRACT_ADDRESS=${VARS[IMPLICATIONS_CONTRACT_ADDRESS]:-}"
  echo "OPENROUTER_API_KEY=${VARS[OPENROUTER_API_KEY]:-}"
  echo "OPENROUTER_MODEL=${VARS[OPENROUTER_MODEL]:-anthropic/claude-3.5-haiku}"
  echo "IPFS_API=${VARS[IPFS_API]:-}"
  echo "IPFS_GATEWAY=${VARS[IPFS_GATEWAY]:-}"
  echo "PORT=${VARS[PORT]:-3000}"
  echo "X402_PAYMENT_ADDRESS=${VARS[X402_PAYMENT_ADDRESS]:-}"
  echo "SERVICE_MARGIN_PERCENT=${VARS[SERVICE_MARGIN_PERCENT]:-20}"
  echo "ETH_USD_PRICE=${VARS[ETH_USD_PRICE]:-3000}"
  echo "GAS_PRICE_MULTIPLIER=${VARS[GAS_PRICE_MULTIPLIER]:-1.2}"
  echo "ESTIMATED_INPUT_TOKENS=${VARS[ESTIMATED_INPUT_TOKENS]:-1000}"
  echo "ESTIMATED_OUTPUT_TOKENS=${VARS[ESTIMATED_OUTPUT_TOKENS]:-200}"
  echo "RATE_LIMIT_WINDOW_MS=${VARS[RATE_LIMIT_WINDOW_MS]:-60000}"
  echo "RATE_LIMIT_MAX_REQUESTS=${VARS[RATE_LIMIT_MAX_REQUESTS]:-10}"
} > "$ROOT/attester/.env"

echo "  wrote $ROOT/attester/.env"

echo ""
echo "Done! Environment configured for network: $NETWORK"
